### ISSUE TITLE
Improve README with usage instructions

### ISSUE THREAD

**Issue by juliohm** [OML-NPA/EasyML.jl#17]
I tried to add the package and `using EasyML` but the Window isn't shown. Have you tested it on Linux? I am using KDE as the desktop environment, I should have most Qt libraries already installed.

**Comment by a-ill** [comment]
I have not tested on linux yet, but it should work. QML.jl downloads all needed QML artifacts during package installation, so libraries should not be an issue.

Not sure that I understood you correctly, but do you mean that you expected a GUI window to appear after running `using EasyML`? If so, then you need to run functions such as `modify_classes`, `design_model` and etc to call respective GUI windows.

**Comment by juliohm** [comment]
Oh, I followed the instructions in the README and there I thought that just loading the package would trigger the GUI. Renaming the issue to "improve README".

**Comment by a-ill** [comment]
Going to do that, thanks!

**Comment by a-ill** [comment]
Added quick guide to the README

**Comment by juliohm** [comment]
Thanks, I think you could even mention that each command will trigger the GUI. Is `using EasyML` really part of the installation?

I will close the issue as it is already in your radar. 👍🏽
